name: CI

on:
  push:
    branches: [ "main" ]
    
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        shell: bash
        run: |
          sudo apt-get update
          sudo apt install dirmngr lsb-release ca-certificates software-properties-common apt-transport-https curl -y
          curl -fSsL https://packages.microsoft.com/keys/microsoft.asc | sudo gpg --dearmor | sudo tee /usr/share/keyrings/powershell.gpg > /dev/null
          echo "deb [arch=amd64,armhf,arm64 signed-by=/usr/share/keyrings/powershell.gpg] https://packages.microsoft.com/ubuntu/22.04/prod/ jammy main" | sudo tee /etc/apt/sources.list.d/powershell.list
          sudo apt update
          sudo apt install powershell

      - name: Run tests
        shell: pwsh
        run: |
          Install-Module Pester, PSScriptAnalyzer -Force -Scope CurrentUser
          ./TestExecutor.ps1
